//REGISTRO DEL USUARIO
###
POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json

   {
    "email":"cherryy@hotmail.com",
    "password":"cherry12345"
   }

//LOGIN DEL USUARIO YA CREADO
###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
    "email":"cherryy@hotmail.com",
    "password":"cherry12345"
}

//registro de reclutadores
###
POST http://localhost:9000/registerRecluiter HTTP/1.1
Content-Type: application/json
   
   {
    "email":"recluiterkass@hotmail.com",
    "password":"recluiter12345"
   }


//LOGIN DEL reclutador YA CREADO
###
POST http://localhost:9000/loginRecluiter HTTP/1.1
Content-Type: application/json

{
    "email":"recluiterkass@hotmail.com",
    "password":"recluiter12345"
}


//REGISTRAR TRABAJOS
###
POST http://localhost:9000/jobOffers HTTP/1.1
Content-Type: application/json

{
    "title": "Delivery Uber Eats",
    "descriptionCompany":"Nos complace ayudar, somos parte del grupo uber, el cual brinda oportunidades a diferentes tipos de personas. en este dia nos encontramos en la necesidad de buscar un delivery el cual cuente con vehiculo propio y se pueda integrar rapidamente " ,
    "salary":"200",
    "location":"Argentina",
    "companyImage":"https://i.ibb.co/McZXsGJ/jumbo-logo-bulevar.png",
    "workingDate":"Media Jornada",
    "experience":"2",
    "createdAt":""
}

//VER TODOS LOS TRABAJOS CREADOS Y DISPONIBLES
### 
GET http://localhost:9000/jobOffers HTTP/1.1

//FILTRAR POR ID 
###
GET http://localhost:9000/jobOffers/62e0a34786bc2a05f5a3d998 HTTP/1.1
Content-Type: application/json


// ELIMINAR POR ID 
###
DELETE http://localhost:9000/jobOffers/62d34f03356b829c015db240 HTTP/1.1
Content-Type: application/json

//ACTUALIZAR POR ID 
###
PATCH http://localhost:9000/jobOffers/62e0a34786bc2a05f5a3d998 HTTP/1.1
Content-Type: application/json

{
    
    "title":"Delivery Didi Food"

}

//Crear REgistro DE CURRICULUM 
###
POST http://localhost:9000/registerCurri HTTP/1.1
Content-Type: application/json

{
    "cedula":"1152692345",
    "name":"Diego Aleman",
    "lastName":"Peruano Xoximilco",
    "age":"28",
    "lastJob":"Jugador de videojuegos",
    "phoneNumber":"3127421351",
    "avatar":"diegoaleman.png",
    "university":"Zenita",
    "exp":"0"
}

###
PATCH http://localhost:9000/registerCurri HTTP/1.1
Content-Type: application/json 

###
GET http://localhost:900/postulados HTTP/1.1
Content-Type: application/json

GET http://localhost:9000/postulados/ HTTP/1.1
Content-Type: application/json


