###
POST http://localhost:9000/register HTTP/1.1
Content-Type: application/json

   {
    "email":"kass@gmail.com",
    "password":"borntodie123"
   }


###
POST http://localhost:9000/login HTTP/1.1
Content-Type: application/json

{
    "email":"kass@gmail.com",
    "password":"borntodie123"
}

###
POST http://localhost:9000/api/jobOffers HTTP/1.1
Content-Type: application/json

{

    "title": "desarrollador frontend",
    "company":" Mazda Inc" ,
    "salary":"200",
    "location":"Francia",
    "companyImage":"imagen.mazda.jpg", 
    "time": ""
}